<div class="register-container">
    <div class="row">
        <div class="col-md-12">
            <div class="text-center m-b-md">
                <h3>Cadastre-se</h3>
            </div>
            <div class="hpanel">
                <div class="panel-body">
                    <form action="#" id="loginForm">
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label>E-mail</label>
                                <input type="" value="" id="" class="form-control" name="">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Senha</label>
                                <input type="password" value="" id="" class="form-control" name="">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Repita a senha</label>
                                <input type="password" value="" id="" class="form-control" name="">
                            </div>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-success">Cadastrar</button>
                            <a class="btn btn-default" href="<?php  echo $this->url('home'); ?>">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>