<div class="login-container">
    <div class="row">
        <div class="col-md-12">
            <div class="text-center m-b-md">
                <h3>Recuperar senha</h3>
            </div>
            <div class="hpanel">
                <div class="panel-body">
                    <p>
                        Você receberá uma nova senha por e-mail.
                    </p>
                        <form action="#" id="loginForm">
                            <div class="form-group">
                                <label class="control-label" for="username">E-mail</label>
                                <input type="text" title="Please enter you email adress" required="" value="" name="username" id="username" class="form-control">
                            </div>
                            <button class="btn btn-success btn-block">Recuperar</button>
                        </form>
                </div>
            </div>
        </div>
    </div>