<?php
$form = $this->form;
$formClass = $this->form;
$this->formElementErrors()
        ->render($form);

$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <div class="text-center m-b-md">
            <h3>Bem-vindo ao QuickPark</h3>
        </div>
        <div class="hpanel">
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formInput($form->get($formClass->getToken())); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('email')); ?>
                    <?php echo $this->formInput($form->get('email')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('password')); ?>
                    <?php echo $this->formInput($form->get('password')); ?>
                    <a class="help-block small" href="#">Esqueci minha senha</a>
                </div>
                <?php echo $this->formSubmit($form->get('entrar')); ?>
                <a class="btn btn-default btn-block" href="#">Cadastre-se</a>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        <strong>QuickPark</strong> - Sistema web para pagamento de estacionamentos <br/> © Copyright 2016 QuickPark Ltda.
    </div>
</div>