<?php
$form = $this->form;
$formClass = $this->form;
$this->formElementErrors()
        ->render($form);

$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formInput($form->get($formClass->getToken())); ?>
<h2 class="form-signin-heading">Please sign in</h2>
<?php echo $this->formLabel($form->get('email')); ?>
<?php echo $this->formInput($form->get('email')); ?>
<?php echo $this->formLabel($form->get('password')); ?>
<?php echo $this->formInput($form->get('password')); ?>
<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
<?php echo $this->form()->closeTag(); ?>
</div>