<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImagemNoticia extends \Admin\Entity\ImagemNoticia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'titulo', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'arquivo', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'ordem', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'ativo', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'noticia_id', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'noticia');
        }

        return array('__isInitialized__', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'titulo', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'arquivo', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'ordem', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'ativo', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'noticia_id', '' . "\0" . 'Admin\\Entity\\ImagemNoticia' . "\0" . 'noticia');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImagemNoticia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCategoria(\Admin\Entity\Noticia $noticia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($noticia));

        return parent::setCategoria($noticia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoticia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoticia', array());

        return parent::getNoticia();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setArquivo($arquivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArquivo', array($arquivo));

        return parent::setArquivo($arquivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArquivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArquivo', array());

        return parent::getArquivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdem($ordem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdem', array($ordem));

        return parent::setOrdem($ordem);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdem', array());

        return parent::getOrdem();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCriacao($dataCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCriacao', array($dataCriacao));

        return parent::setDataCriacao($dataCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataModificacao($dataModificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataModificacao', array($dataModificacao));

        return parent::setDataModificacao($dataModificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModificacao', array());

        return parent::getDataModificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoticiaId($noticia_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoticiaId', array($noticia_id));

        return parent::setNoticiaId($noticia_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoticiaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoticiaId', array());

        return parent::getNoticiaId();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
