<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Noticia extends \Admin\Entity\Noticia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'usuario_aprovacao_id', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'titulo', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'descricao', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'chamada', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'nivel', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'data_publicacao', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'status', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'ativo', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'categoria', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'imagens');
        }

        return array('__isInitialized__', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'usuario_aprovacao_id', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'titulo', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'descricao', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'chamada', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'nivel', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'data_publicacao', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'status', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'ativo', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'categoria', '' . "\0" . 'Admin\\Entity\\Noticia' . "\0" . 'imagens');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Noticia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getImagens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagens', array());

        return parent::getImagens();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagens(\Doctrine\Common\Collections\ArrayCollection $imagens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagens', array($imagens));

        return parent::setImagens($imagens);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioAprovacaoId($usuarioAprovacaoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioAprovacaoId', array($usuarioAprovacaoId));

        return parent::setUsuarioAprovacaoId($usuarioAprovacaoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioAprovacaoId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioAprovacaoId', array());

        return parent::getUsuarioAprovacaoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setChamada($chamada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChamada', array($chamada));

        return parent::setChamada($chamada);
    }

    /**
     * {@inheritDoc}
     */
    public function getChamada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChamada', array());

        return parent::getChamada();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivel($nivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivel', array($nivel));

        return parent::setNivel($nivel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivel', array());

        return parent::getNivel();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataPublicacao($dataPublicacao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataPublicacao', array($dataPublicacao));

        return parent::setDataPublicacao($dataPublicacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataPublicacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataPublicacao', array());

        return parent::getDataPublicacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\Admin\Entity\Categoria $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
