<?php

$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {
JS;

if ($this->flashMessenger()->hasErrorMessages()) {
    echo <<<JS
        toastr.error('
JS;
    echo addslashes($this->flashMessenger()->getErrorMessages()[0]);
    echo <<< JS
    ');
JS;
}

if ($this->flashMessenger()->hasSuccessMessages()) {
    echo <<<JS
        toastr.success('
JS;
    echo addslashes($this->flashMessenger()->getSuccessMessages()[0]);
    echo <<< JS
    ');
JS;
}


if ($this->flashMessenger()->hasWarningMessages()) {
    echo <<<JS
        toastr.warning('
JS;
    echo addslashes($this->flashMessenger()->getWarningMessages()[0]);
    echo <<< JS
    ');
JS;
}


if ($this->flashMessenger()->hasInfoMessages()) {
    echo <<<JS
        toastr.info('
JS;
    echo addslashes($this->flashMessenger()->getInfoMessages()[0]);
    echo <<< JS
    ');
JS;
}

echo <<<JS
    });
JS;

$this->inlineScript()->captureEnd();
$this->flashMessenger()->clearMessages();