<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'TpMinify', // Minify de css e Js
        'DoctrineModule',
        'DoctrineORMModule',
        'Base',
        'Login',
        'Admin',
        'Ticket'
    ),
    
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    ),
    'service_manager' => array(
        'factories' => array (
            'translator' => 'Zend\I18n\Translator\TranslatorServiceFactory',
            'ZendCacheStorageFactory' => function() {
                return Zend\Cache\StorageFactory::factory(
                    array(
                        'adapter' => array(
                            'name' => 'filesystem',
                            'options' => array(
                                'dirLevel' => 2,
                                'cacheDir' => 'data/cache',
                                'dirPermission' => 0755,
                                'filePermission' => 0666,
                                'namespaceSeparator' => '-db-',
                                'ttl' => 3600 * 3
                            ),
                        ),
                        'plugins' => array('serializer'),
                    )
                );
            },
        ),
        'aliases' => array(
            'cache' => 'ZendCacheStorageFactory',
        ),
    ),
);
