<?php echo $this->partial('admin/funcionario/listheader.phtml'); ?>
<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <!--<a class="closebox"><i class="fa fa-times"></i></a>-->
                    </div>
                    <a href="<?php echo $this->url('admin/default', array('controller' => 'funcionario', 'action' => 'insert')); ?>" class="btn btn-success">
                        <i class="fa fa-plus"></i> Adicionar funcionário
                    </a>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" ui-jp="dataTable" class="table table-striped b-t b-b" style="width: 100%" ui-options="{
                           sAjaxSource: '<?php echo $this->url('admin/default', array('controller' => 'funcionario', 'action' => 'list')); ?>',
                           aDataSort: [[1,'desc']]
                           }">
                        <thead>
                            <tr>
                                <th></th>
                                <th style="width:40%">Nome</th>
                                <th style="width:20%">CPF</th>
                                <th style="width:40%">E-mail</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>