<?php

namespace Base\Entity;

/**
 * EnderecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalRepository extends \Doctrine\ORM\EntityRepository {
    
}
