<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title><?php echo $this->translate('Login'); ?></title>

        <!--Place favicon.ico and apple-touch-icon.png in the root directory--> 
        <link rel="shortcut icon" type="image/ico" href="favicon.ico" />
        
        <?php $this->headLink()->prependStylesheet($this->basePath('/libs/fontawesome/css/font-awesome.min.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/css/styles.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/libs/bootstrap/dist/css/bootstrap.min.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/libs/metisMenu/dist/metisMenu.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/libs/animate.css/animate.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/libs/toastr/build/toastr.min.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css')); ?>
        <?php $this->headLink()->prependStylesheet($this->basePath('/fonts/pe-icon-7-stroke/css/helper.css')); ?>
        
        <?php echo $this->headLink(); ?>
    </head>
    <body class="blank">

        <!-- Simple splash screen-->
        <div class="splash">
            <div class="color-line"></div>
            <div class="splash-title">
                <h1>Carregando...</h1>
                <p>Por favor, aguarde</p>
                <div class="spinner">
                    <div class="rect1"></div>
                    <div class="rect2"></div>
                    <div class="rect3"></div>
                    <div class="rect4"></div>
                    <div class="rect5"></div>
                </div>

            </div>
        </div>
        <!--[if lt IE 7]>
        <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <div class="color-line"></div>

        <div class="login-container">
                <?php echo $this->partial('layout/flashMessage'); ?>
                <?php echo $this->content; ?>
            <button class="homerDemo1 btn btn-info btn-sm">Run example</button>
        </div>
    </body>
    <?php $this->headScript()->prependFile($this->basePath('/min?g=login-js')); ?>
    <?php $this->headScript()->prependFile($this->basePath('/toastr/build/toastr.min.js')); ?>
    <?php echo $this->headScript(); ?>
</html>

<script>

    $(function () {
        // Toastr options
        toastr.options = {
            "debug": false,
            "newestOnTop": false,
            "positionClass": "toast-top-center",
            "closeButton": true,
            "toastClass": "animated fadeInDown",
        };

        $('.homerDemo1').click(function (){
            toastr.info('Info - This is a custom Homer info notification');
        });

        $('.homerDemo2').click(function (){
            toastr.success('Success - This is a Homer success notification');
        });

        $('.homerDemo3').click(function (){
            toastr.warning('Warning - This is a Homer warning notification');
        });

        $('.homerDemo4').click(function (){
            toastr.error('Error - This is a Homer error notification');
        });

    });
</script>