<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title><?php echo $this->translate('Login'); ?></title>

        <!--Place favicon.ico and apple-touch-icon.png in the root directory--> 
        <link rel="shortcut icon" type="image/ico" href="favicon.ico" />

        <?php // $this->headLink()->appendStylesheet($this->basePath('/min?g=login-css')); ?>
        <!-- Vendor styles -->
        <?php $this->headLink()->appendStylesheet($this->basePath('/libs/fontawesome/css/font-awesome.min.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/libs/metisMenu/dist/metisMenu.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/libs/animate.css/animate.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/libs/bootstrap/dist/css/bootstrap.min.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/libs/toastr/build/toastr.min.css')); ?>
        <!-- App styles -->
        <?php $this->headLink()->appendStylesheet($this->basePath('/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/fonts/pe-icon-7-stroke/css/helper.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/css/styles.css')); ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/css/static_custom.css')); ?>

        <?php echo $this->headLink(); ?>
    </head>
    <body class="blank">
        <!-- Simple splash screen-->
        <div class="splash">
            <div class="color-line"></div>
            <div class="splash-title">
                <h1>Carregando...</h1>
                <p>Por favor, aguarde</p>
                <div class="spinner">
                    <div class="rect1"></div>
                    <div class="rect2"></div>
                    <div class="rect3"></div>
                    <div class="rect4"></div>
                    <div class="rect5"></div>
                </div>

            </div>
        </div>
        <!--[if lt IE 7]>
        <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <div class="color-line"></div>

            <?php echo $this->partial('layout/flashMessage'); ?>
            <?php echo $this->content; ?>
        
        <div class="row">
            <div class="col-md-12 text-center">
                <strong>QuickPark</strong> - Sistema web para pagamento de estacionamentos<br/>
                © Copyright 2016 QuickPark Ltda.
            </div>
        </div>
    </body>
    <?php // $this->headScript()->appendFile($this->basePath('/min?g=login-js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/libs/jquery/dist/jquery.min.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/libs/jquery-ui/jquery-ui.min.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/libs/slimScroll/jquery.slimscroll.min.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/libs/bootstrap/dist/js/bootstrap.min.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/libs/metisMenu/dist/metisMenu.min.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/js/homer.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/libs/toastr/build/toastr.min.js')); ?>
    <?php $this->headScript()->appendFile($this->basePath('/js/scripts.js')); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->inlineScript(); ?>
</html>